### ISSUE TITLE
Incomplete data in forecast

### ISSUE THREAD

**Issue by JorickVel** [RubendeBruin/WaveDave#1]
Soms heeft een data punt geen informatie (zie voorbeeld 1D info spectral data). Bij foutmelding graag incomplete datapunten automatisch verwijderen

![afbeelding](https://github.com/RubendeBruin/WaveDave/assets/166730208/0cb83866-c33c-4130-a202-f149cf8f133a)

**Comment by JorickVel** [comment]
example data attached 
[marine_forecast_report_48127827-240410-050043_20240410.csv](https://github.com/RubendeBruin/WaveDave/files/14956601/marine_forecast_report_48127827-240410-050043_20240410.csv)

**Comment by RubendeBruin** [comment]
fixed,
columns with missing values will not be read,
except is that column is a text column, then it is ok
in either case reading continues so if valid data is present after the missing block then that data is still read
