### ISSUE TITLE
Graph on limits y-axis 

### ISSUE THREAD

**Issue by JorickVel** [RubendeBruin/WaveDave#11]
It seems the graphs are not copped above and below the limits of the y-axis. 

![afbeelding](https://github.com/RubendeBruin/WaveDave/assets/166730208/5d0be709-e9d8-4bc6-a924-a9d96d2ac532)

**Comment by RubendeBruin** [comment]
this is a pdf issue

**Comment by RubendeBruin** [comment]
Worked-around by using png instead of svg
