### ISSUE TITLE
Set timezone with local_timezone_utc_plus

### ISSUE THREAD

**Issue by JorickVel** [RubendeBruin/WaveDave#12]
Im trying to set the timezones for the various data types using the following command however the time is not changed in the plots (does work for 1D spec data, 2D spec data or the wave rider buoy). Assistance needed. 

forecast2D3 = Spectra.from_octopus(files[-1])
forecast2D3.local_timezone_utc_plus = 100

**Comment by JorickVel** [comment]
Got it working. Correct command is forecast2D1 = Spectra.from_octopus(files[-4],source_in_utc_plus=-100)

Note that a UTC timezone +2 requires an input of -2. Should be reversed?

**Comment by JorickVel** [comment]
I made a wrong assumption. It seems wavedave automatically sets the time zone. You are required to set the timezone of the data relative to UTC.

Timezone can be adjusted with e.g. Settings.LOCAL_TIMEZONE=6

**Comment by JorickVel** [comment]
Issue: when setting the Settings.LOCAL_TIMEZONE=2 it seems the actual timezone is set to +4UTC. This leaves me puzzled how the time of the data and the timezone is set.

**Comment by RubendeBruin** [comment]
Confirmed,

Settings.LOCAL_TIMEZONE was applied twice, first when creating a LineSource and then again when plotting.

The LineSource is now in UTC, so the offset is only applied when plotting.

Can you confirm and close?

**Comment by JorickVel** [comment]
Seems the issue is not yet resolved. I have re-installed wave dave (uninstall en install via pip). Time zone in figure subscript is not yet adjusted and the wave rider buoy data still has a +2 hours offset.  

Used script
[example report.txt](https://github.com/RubendeBruin/WaveDave/files/14988297/example.report.txt)

UTC in figure should be +2
![afbeelding](https://github.com/RubendeBruin/WaveDave/assets/166730208/016dd194-ad1c-41a7-8ce4-53bceaa1b963)


Wave rider data +2 hours offset
![afbeelding](https://github.com/RubendeBruin/WaveDave/assets/166730208/d469ebf2-798f-4062-8770-13a4acad9035)

**Comment by RubendeBruin** [comment]
Rewritten reader to get the time from the time-stamp in the file, that is always UTC.
No need anymore to supply the timezone in the read function
