### ISSUE TITLE
Header format roseplots

### ISSUE THREAD

**Issue by JorickVel** [RubendeBruin/WaveDave#13]
Can you change the header format of the roseplot a little?

Current format
![afbeelding](https://github.com/RubendeBruin/WaveDave/assets/166730208/a8aa7cf3-a2ec-4472-b37b-fb70fa683648)

Proposed format (add date after event name, add break after integrated data)

![afbeelding](https://github.com/RubendeBruin/WaveDave/assets/166730208/ac0c3010-8691-4aad-a085-6e6d250ee80b)

**Comment by RubendeBruin** [comment]
The time has been removed from the title, it was not adding much value anyways
