### ISSUE TITLE
Major grid distance on x-axis should be 1 day

### ISSUE THREAD

**Issue by JorickVel** [RubendeBruin/WaveDave#14]
Can you include an option which forces the x-axis step to 1day

Below figure not wished format (2day step)

![afbeelding](https://github.com/RubendeBruin/WaveDave/assets/166730208/cb981a54-f33e-43f7-b3e8-fcf9e34ad86b)

**Comment by RubendeBruin** [comment]
![image](https://github.com/RubendeBruin/WaveDave/assets/34062862/efda25e5-7faa-4967-a775-55b71169e1d8)

fixed
