### ISSUE TITLE
Worst and best heading

### ISSUE THREAD

**Issue by JorickVel** [RubendeBruin/WaveDave#16]
It would be very nice if two heading options are added to the response calculation, worst possible and best possible heading. The worst heading shows the highest expected response for a certain RAO in combination with a a wave data set for all time steps. The best the lowest response. 

The calculated heading (worst or best) can be showed via arrows in the response graph or a separate plot with heading in time. 

The response is calculated for a 5deg heading step (or different pending on the calculation time).

**Comment by RubendeBruin** [comment]
Added: https://github.com/RubendeBruin/WaveDave?tab=readme-ov-file#vessel-heading-optimization

**Comment by JorickVel** [comment]
Thanks!
