### ISSUE TITLE
Setting heading_definition

### ISSUE THREAD

**Issue by JorickVel** [RubendeBruin/WaveDave#17]
When changing the heading definition to _RAOHeadingDefinition.VESSEL_BOUND I run into the error that _RAOHeadingDefinition_ is not defined. Im now using a work around setting the heading_definition to _RAO.test_rao().heading_definition_, though this is not a very nice solution.. :)

**Comment by JorickVel** [comment]
```hallo```

**Comment by JorickVel** [comment]
To change the heading definition I use the following code 

```RAOs[name][prop].heading_definition=RAO.test_rao().heading_definition```

This code will result in a NameError: name 'RAOHeadingDefinition' is not defined

```RAOs[name][prop].heading_definition=RAOHeadingDefinition.VESSEL_BOUND ```

**Comment by RubendeBruin** [comment]
As of the next version RAOHeadingDefinition is imported when doing `from wavedave import *`

for the current version you can use:
```python
from wavedave.rao.rao import RAO, RAOHeadingDefinition
```
