### ISSUE TITLE
Add x-axis limits to Graph

### ISSUE THREAD

**Issue by JorickVel** [RubendeBruin/WaveDave#18]
Im unable to manually set the ylim of standard figures. Can you add this option or if already implemented explain how to set the ylim. Similar I would also like to be able to manually set the x-lim (by giving 2 dates). 

![afbeelding](https://github.com/RubendeBruin/WaveDave/assets/166730208/02aa957a-d571-46d3-9558-7f0d4c9d53a4)

**Comment by RubendeBruin** [comment]
Added to Graph, see: https://github.com/RubendeBruin/WaveDave/blob/main/examples/Formatting_the_graphs.ipynb
