### ISSUE TITLE
Response figure format

### ISSUE THREAD

**Issue by JorickVel** [RubendeBruin/WaveDave#19]
Can you makes some changes in the format of the response plots? See below in red

![afbeelding](https://github.com/RubendeBruin/WaveDave/assets/166730208/f043debf-e0b6-4297-8854-91c6328237f1)

**Comment by RubendeBruin** [comment]
Enforced:
- all lines shall have the same statistics type (SDA, MPM, etc)
- all lines shall have the same unit

**If the line-sources have the same label:**
- label as title
- statistics type and unit as title
- data_source as legend


Example title: Vessel Roll [deg]  (SDA)


**If the line-sources do not have the same label:**
- label as legend
- statistics type and unit as title
- if datasources are identical: put as title, if not then add to legend

**Comment by RubendeBruin** [comment]
Same label:
![image](https://github.com/RubendeBruin/WaveDave/assets/34062862/411f89c5-2f2b-4a6c-8c10-5bf41de45325)

**Comment by RubendeBruin** [comment]
![image](https://github.com/RubendeBruin/WaveDave/assets/34062862/504d1b90-d9eb-4c45-8423-af23bef77cef)

**Comment by JorickVel** [comment]
Yes indeed! 

Two ideas
(1) In case sMPM will you also show the STF factor? So for example (SMPM with STF 2.0)

(2) In the second option, can you add in the wave data name? Example

![afbeelding](https://github.com/RubendeBruin/WaveDave/assets/166730208/104d4e6b-5863-4257-bc36-c48178558cef)

**Comment by RubendeBruin** [comment]
Two ideas
(1) In case sMPM will you also show the STF factor? So for example (SMPM with STF 2.0)

That will be taken care of by the newly introduced StatisticsType class

(2) In the second option, can you add in the wave data name? Example

If all the waves are from the same source then that source is the figure title ('octopus' in this example)

**Comment by RubendeBruin** [comment]
@JorickVel 
can you close this issue when you are happy?
