### ISSUE TITLE
Extra data in forecast in string format

### ISSUE THREAD

**Issue by JorickVel** [RubendeBruin/WaveDave#2]
Blijkbaar voegt Infoplaza (af en toe) extra data toe als tekst formaat. Kunnen we een try procedure invoegen en anders de string laten voor wat het is. 

![afbeelding](https://github.com/RubendeBruin/WaveDave/assets/166730208/34c487d4-8ced-49cd-8afb-867b4b3c6613)

![afbeelding](https://github.com/RubendeBruin/WaveDave/assets/166730208/2ce10ac1-3afe-4ec5-9db1-c3c6a0f49b36)

**Comment by JorickVel** [comment]
example data attached 

[marine_forecast_report_48127827-240411-170047_20240411.csv](https://github.com/RubendeBruin/WaveDave/files/14956605/marine_forecast_report_48127827-240411-170047_20240411.csv)

**Comment by RubendeBruin** [comment]
Ze passen de header netjes aan, daar staat nu `text` boven die colom

**Comment by RubendeBruin** [comment]
![image](https://github.com/RubendeBruin/WaveDave/assets/34062862/811b062c-88bd-4a01-9ae0-2f453dce2219)

Gefixt in de komende versie
