### ISSUE TITLE
Response calculation RAO with sharp peak

### ISSUE THREAD

**Issue by JorickVel** [RubendeBruin/WaveDave#21]
When performing a response calculation for an RAO with a sharp peak (e.g. block motions) the response calculation seems to introduces an error.

Example RAOs send by mail. Difference between Orcaflex for pitch 2%, and for block x motion 300%. 

Orcaflex results pitch SSA 1.16deg, and block x SSA 2.56m
Results Wavedave Pitch SSA 1.13deg and block a SSA 7.82m

Code to calculate response:

#global_rao = RAOs['HL10_Hoistwire_25m']['HL10']['Pitch'].to_global(vessel_heading = 0) 
global_rao = RAOs['HL10_Hoistwire_25m']['Equalizer']['Horizontal motion y'].to_global(vessel_heading = 0)  

Jonswap=Spectra.create_jonswaps(Hs=2,Tp=7,gamma=3.3,directions=0,spreading=10)
response_test = global_rao.wave_response(Jonswap)
response_test.plot_1d_spectra()
response_test.SSA

Input Orcaflex

![afbeelding](https://github.com/RubendeBruin/WaveDave/assets/166730208/e5365c13-96e9-497e-9502-3e8e44172fc1)

**Comment by JorickVel** [comment]
Code to load RAO files

#load RAOs
dir = r'C:\Orcaflex\RAO'

RAO_files = Path(dir).glob('*.yml')
RAO_files = list(RAO_files)
RAOs=dict()

#load all RAOs from folder and save in dict sorted on Orcaflex model name, object name and variable name. 
for f in RAO_files:
    
    rao=RAO.from_file(f)
    for model, obj,name,prop, varname, unit  in [rao.metadata]:
        try:
           RAOs[model]
        except:
            RAOs[model]=dict()       
        try:
           RAOs[model][name]
        except:
            RAOs[model][name]=dict()
        RAOs[model][name][varname]=rao

**Comment by RubendeBruin** [comment]
Hi @JorickVel 

I can not spot anything off in the response calculation by wavedave:

![image](https://github.com/RubendeBruin/WaveDave/assets/34062862/254b2925-6e8e-48a3-a6ab-391ab4eb1dab)

With a finer grid the response gets higher rather than lower in this case.

Can you provide 
- a screenshot of the response spectrum as calculated by orcaflex? 
- a screenshot of the RAO that is calculated by orcaflex when the sea-state is set to the one above (Hs=2,Tp=7,gamma=3.3,spreading=10)

**Comment by JorickVel** [comment]
When using wave spreading Im unable to back calculate an RAO in Orcaflex. Though the response spectra is shown below. Hoistwire length 25m. 

![afbeelding](https://github.com/RubendeBruin/WaveDave/assets/166730208/fca7d407-6361-4a7c-92fa-065504fa8320)


Case Hs 2m, Tp 9sec, gamma 3.3 no wave spreading with RAO. 

![afbeelding](https://github.com/RubendeBruin/WaveDave/assets/166730208/2f83a901-a40e-4672-ac92-6b4393ab2d96)

**Comment by JorickVel** [comment]
SSA Tp 7sec = 4 * sqrt(1.62) /2 = 2.54m
SSA Tp 9sec = 4 * sqrt*119.8)/2 = 21.89m

**Comment by RubendeBruin** [comment]
In the first screenshot the natural period seems to be at ~0.11 Hz, In the second screenshot it is at ~ 0.9 Hz. Are these the same models?

**Comment by RubendeBruin** [comment]
With spreading=20 for Hs2, Tp9 I get:
![image](https://github.com/RubendeBruin/WaveDave/assets/34062862/9a30ff09-eb4e-433f-9da6-82394cc1ab10)
which is not too far off the second screenshot, only the RAO has a different peak... ?

**Comment by JorickVel** [comment]
Agree that the RAO peaks do not match. I'll have a look. My input seems correct (hoist wire length is coded in the name so hard to make an error), though if the output is correct in dont know. 

The models are the same. I also run the Tp7 seconds in Orcaflex time domain. Result SSA 6.3m. Not alligned with Orcaflex freq domain results, though same order of magnitude as wavedave.

**Comment by JorickVel** [comment]
I re-send you the RAOs, they were indeed off by 5m hoist wire length.

Also I noticed that for the Tp is 9 sec Orcaflex calculates an SSA of 21.9m and wavedave 21.8m. Which is a good match

![afbeelding](https://github.com/RubendeBruin/WaveDave/assets/166730208/710e550c-1b95-402a-be9c-999a2092ca52)

However for the Tp is 7sec Orcaflex calculates an SSA of 2.54m and wavedave 5.3m. However Orcaflex timedomain results give 6.3m. Seeing the Orcaflex response spectra I tend to say the Orcaflex freq domain results are incorrect.

**Comment by RubendeBruin** [comment]
@JorickVel, Shall I close this issue or do you want to keep it open till the orcaflex side is cleared up?

**Comment by JorickVel** [comment]
You may close this issue.
