### ISSUE TITLE
Plot issue when using ylim 

### ISSUE THREAD

**Issue by JorickVel** [RubendeBruin/WaveDave#23]
When adding a limit to the y-axis the figure is not printed correctly in the pdf (guess again issue with fpdp).

figure in report

![afbeelding](https://github.com/RubendeBruin/WaveDave/assets/166730208/cc491a56-f456-4914-8447-785998b5f1bd)

figure in Jupyterlab is correct

![afbeelding](https://github.com/RubendeBruin/WaveDave/assets/166730208/0f2913af-1c7c-40dc-9de8-4241e9f8c041)

**Comment by RubendeBruin** [comment]
yes, this is fpdf
Same work-around as for other plots.

Agree to change plot type from vector to raster?

**Comment by JorickVel** [comment]
Yup I think that gives us the best solution for now. So far no issues with the image quality of report size.

**Comment by RubendeBruin** [comment]
Updated default to .png with DPI=300

To go back to vector use: `report.image_format = 'svg'`
