### ISSUE TITLE
Figure format responses

### ISSUE THREAD

**Issue by JorickVel** [RubendeBruin/WaveDave#24]
Can you change the format of the response figures a little (really like to automatic titles!)

Move file name to bottom of figure
Change naming of statistics (DA or SA and Maximum to MPM)

![afbeelding](https://github.com/RubendeBruin/WaveDave/assets/166730208/6234e9a0-d046-4425-8990-aa31dd388768)

**Comment by RubendeBruin** [comment]
@JorickVel 
please 

1. propose short names for all statistic types as in https://github.com/RubendeBruin/WaveDave#statistics-type

for example:
Maximum --> MPM
Significant --> SIG
etc.

but isn't MPM STF over elaborate as STF already implies a Maximum

2. Move RAO filenames to a separate issue.

**Comment by JorickVel** [comment]
I would propose to use the following naming

SA or DA
SIG or MPM with STF 2.0 or MPM with n=1000

Titles are built: [RAO object name] [RAO property name] [Statistics type] [heading]

HL10 roll (SA SIG) heading = 10deg
HL10 roll (DA MPM with STF 2.0) heading = 10deg

**Comment by JorickVel** [comment]
Opened a seperate issue for RAO file names.

**Comment by RubendeBruin** [comment]
" [RAO object name] [RAO property name] [Statistics type] [heading]"

At the moment RAO object and RAO property are not stored separately. It is just a single title. Should that be added? And if so, how to treat the "state" such as the hook-height?

**Comment by JorickVel** [comment]
I understand now. The title is now similar to the description of the RAO correct? I can change the description to suit the title, so no change needed there. 

So title will be [RAO.description] [Statistics type] [heading]
