### ISSUE TITLE
Y as minimum vast op 0

### ISSUE THREAD

**Issue by JorickVel** [RubendeBruin/WaveDave#3]
Graag de minimum waardes van de y as standaard naar 0 laten lopen

![afbeelding](https://github.com/RubendeBruin/WaveDave/assets/166730208/4f413e8b-01a0-49c5-a0c9-3c93f90d11e1)

**Comment by RubendeBruin** [comment]
Fixed: 

was alleen zo voor de bands-plot

![image](https://github.com/RubendeBruin/WaveDave/assets/34062862/3fb33a5a-5062-439a-a3d0-c2997bbf7e22)
