### ISSUE TITLE
Pijlen spectral breakdown

### ISSUE THREAD

**Issue by JorickVel** [RubendeBruin/WaveDave#4]
Graag format van de direction pijlen van de spectral breakdown gelijk maken een die van de standaard plotjes

![afbeelding](https://github.com/RubendeBruin/WaveDave/assets/166730208/ebc7ff0f-51c7-4c9d-a709-0b779a62de06)
Mooie pijltjes!

![afbeelding](https://github.com/RubendeBruin/WaveDave/assets/166730208/4f5dcf72-5f01-4b22-aa31-87bfba305ab1)
Niet zulke mooie pijltjes

**Comment by RubendeBruin** [comment]
Fixed:
![image](https://github.com/RubendeBruin/WaveDave/assets/34062862/6033788c-ed49-48d3-aae4-2d3395f86045)
