### ISSUE TITLE
Title spectral breakdown and energy distribution verwijderen

### ISSUE THREAD

**Issue by JorickVel** [RubendeBruin/WaveDave#5]
Graag de automatische titels van de spectral breakdown and energy distribution verwijderen

![afbeelding](https://github.com/RubendeBruin/WaveDave/assets/166730208/2102ccaa-800e-467a-a1a7-b33fa0d2b8d5)

![afbeelding](https://github.com/RubendeBruin/WaveDave/assets/166730208/80274df8-03b9-403f-9c1e-abb8b8244deb)

**Comment by RubendeBruin** [comment]
you can remove these by setting `header_text` to "" or None

Eg:
```python
breakdown_section = BreakdownSection()
breakdown_section.header_text = ''
```
