### ISSUE TITLE
Standaard datum formaat op x-as

### ISSUE THREAD

**Issue by JorickVel** [RubendeBruin/WaveDave#7]
Graag het standaard datum formaat veranderen van  de verschillende figuren

van dit
![afbeelding](https://github.com/RubendeBruin/WaveDave/assets/166730208/1618e661-a1ea-4e59-97fb-da5cd729b375)

naar dit
![afbeelding](https://github.com/RubendeBruin/WaveDave/assets/166730208/5c2737ce-6647-490b-b48e-c49c5c3f00bd)

**Comment by RubendeBruin** [comment]
Will not implement. 09-Apr is typically dutch.
The date-format can be controlled globally by setting:

```python
import wavedave.settings as Settings
Settings.DATE_FORMAT = "%a %d %b\n%H:%m"
```

**Comment by JorickVel** [comment]
The option of setting the date does (no longer) seem to work. Did work before. See example file rose plots. Here date_format is set though plot date does not change.

**Comment by RubendeBruin** [comment]
Please check again with new version, for me it does work in the rose-plots as well: 
![image](https://github.com/RubendeBruin/WaveDave/assets/34062862/05bb6ea5-3cef-464c-9b4d-6b30072b70df)
