### ISSUE TITLE
Quiver spacing spectral breakdown

### ISSUE THREAD

**Issue by JorickVel** [RubendeBruin/WaveDave#8]
Can you add an option to change the quiver spacing of the forecasts in the spectral breakdown? Im only able to change the spacing of the wave rider buoy data. Also it would be nice to set standard quiver spacing to 6. 

Example input

breakdown_section.quiver_spacing =5

**Comment by RubendeBruin** [comment]
```python
breakdown_section = BreakdownSection()
breakdown_section.header_text = ''
breakdown_section.directions_buoy_spacing = 10
breakdown_section.directions_forecast_spacing = 5
```

![image](https://github.com/RubendeBruin/WaveDave/assets/34062862/263e5082-70a2-4d13-84d3-0148b3195dc9)
